services:
  ewm-service:
    build: basic-service
    image: ewm-basic_service
    container_name: ewm-basic_service
    ports:
      - "8080:8080"
    depends_on:
      stats-service:
        condition: service_started
      ewm-service_db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - EWM_STATISTICS_URL=http://stats-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service_db:5433/ewm_main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456

  stats-service:
    build: statistics/server-module
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      ewm-stat_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stat_db:5432/stat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456

  ewm-stat_db:
    image: postgres:16.1
    container_name: ewm-stat_db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service_db:
    image: postgres:16.1
    container_name: ewm-service_db
    ports:
      - "6542:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ewm_main
    command: [ "postgres", "-p", "5433" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER} -p 5433" ]
      timeout: 5s
      interval: 5s
      retries: 10
