services:
  ewm-service:
    build: basic-service
    image: ewm-basic_service
    container_name: ewm-basic_service
    ports:
      - "8083:8083"
    depends_on:
      - stats-server
    environment:
      - EWM_STATISTICS.url=http://stats-server:9090

  stats-server:
    build: statistics/gateway-module
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
#    depends_on:
#      stats-service
    environment:
      - EWM_STAT_SERVICE_URL=http://stats-service:8082

  stats-service:
    build: statistics/service-module
    image: stats-service
    container_name: stats-service
    ports:
      - "8082:8082"
    depends_on:
      ewm-stat_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stat_db:5432/stat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456

  ewm-stat_db:
    image: postgres:16.1
    container_name: ewm-stat_db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: stat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      timeout: 5s
      interval: 5s
      retries: 10
